version: 2

models:

  - name: int_local_bike__brands
    description: "List of the bike's brands sold by the company"
    columns:
      - name: brand_id
        description: "Unique identify (Primary key) of brand"
        tests:
          - not_null
          - unique

      - name: brand_name
        description: "Name of the bike's brand"
        tests:
          - not_null
          - unique

  - name: int_local_bike__categories
    description: "List of the bike's categories sold by the company"
    columns:
      - name: category_id
        description: "Unique identify (Primary key) of category"
        tests:
          - not_null
          - unique
          
      - name: category_name
        description: "Name of the bike's category"
        tests:
          - not_null
          - unique

  - name: int_local_bike__customers
    description: "List of the customers"
    columns:
      - name: customer_id
        description: "Unique identify (Primary key) of customer"
        tests:
          - not_null
          - unique

      - name: customer_full_name
        description: "Full name of the customer"
        tests:
          - not_null

      - name: customer_first_name
        description: "First name of the customer"
        tests:
          - not_null
          
      - name: customer_last_name
        description: "Last name of the customer"
        tests:
          - not_null
          
      - name: customer_phone
        description: "Phone number of the customer"
          
      - name: customer_email
        description: "Email address of the customer"
        tests:
          - not_null
          - unique
          
      - name: customer_street
        description: "Address street of the customer"
          
      - name: customer_city
        description: "City of the customer"
        tests:
        - not_null

      - name: customer_state
        description: "State of the customer"
        tests:
        - not_null

      - name: customer_zip_code
        description: "Zip code of the customer"
        tests:
        - not_null

  - name: int_local_bike__managers
    description: "List of the staffs who are managers"
    columns:
      - name: manager_id
        description: "Unique identify (Primary key) of manager"
        tests:
          - not_null
          - unique

      - name: manager_full_name
        description: "Full name of the manager"
        tests:
          - not_null

      - name: manager_email
        description: "Email address of the manager"
        tests:
          - not_null

  - name: int_local_bike__order_items
    description: "Details of the order with items"
    columns:
      - name: order_items_id
        description: "Unique identify (Primary key) of order_items. It's a concatenation of order_id and item_id"
        tests:
          - not_null
          - unique

      - name: order_id
        description: "Secondary key to join orders table"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__orders')
                field: order_id

      - name: product_id
        description: "Secondary key to join products table"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__products')
                field: product_id

      - name: order_quantity
        description: "Quantity of the product sell in the order"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: unit_price
        description: "Unit price of the product"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "> 0"

      - name: discount
        description: "Discount in percent offer on the product"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "BETWEEN 0 AND 1"

      - name: order_item_total_amount
        description: "Total amount of the line of the order detail"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "> 0"

  - name: int_local_bike__orders
    description: "Header of the orders"
    columns:
      - name: order_id
        description: "Unique identify (Primary key) for the order"
        tests:
          - not_null
          - unique

      - name : customer_id
        description: "Secondary key to join customers table. Identifiant of the customer who buy the order"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__customers')
                field: customer_id

      - name : order_status
        description: "Identifiant of the status 1, 2, 3 or 4 (shipped)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "IN (1, 2, 3, 4)"

      - name : order_date
        description: "Date of the order"
        tests:
          - not_null

      - name : required_date
        description: "Date of shipping ask by the customer"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: ">= order_date"

      - name : shipped_date
        description: "Real shipped date of the order. NULL if not delivered yet."
        tests:
        - dbt_utils.expression_is_true:
                expression: " >= order_date OR shipped_date IS NULL"

      - name: order_is_late
        description: "Take 1 when the delivery is late compare to the required date. And 0 else."
        tests: 
          - not_null
          - dbt_utils.expression_is_true:
                expression: "IN (0, 1)"

      - name : store_id
        description: "Secondary key to join stores table. Identifiant of the store attached to the order"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__stores')
                field: store_id

      - name : staff_id
        description: "Secondary key to join staffs table. Identifiant of the staff who in charge of the order"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__staffs')
                field: staff_id

      - name: order_total_amount
        description: "Total amount of the order"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "> 0"

  - name: int_local_bike__products
    description: "List of the bikes sold by the company"
    columns:
      - name: product_id
        description: "Unique identify (Primary key) of the product"
        tests:
          - not_null
          - unique

      - name: product_name
        description: "Name of the product"
        tests:
          - not_null

      - name: brand_id
        description: "Secondary key to join the brands table. Id of the product's brand"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__brands')
                field: brand_id

      - name: category_id
        description: "Secondary key to join the categories table. Id of the product's category"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__categories')
                field: category_id

      - name: model_year
        description: "Year of production of the product"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: ">= 2000"

      - name: product_unit_price
        description: "Unit price of the product"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "> 0"

  - name: int_local_bike__staffs
    description: "List of the staff employed by the company"
    columns:
      - name: staff_id
        description: "Unique identify (Primary key) of the staff member"
        tests:
          - not_null
          - unique
      - name: staff_full_name
        description: "Full name of the staff member"
        tests:
          - not_null

      - name: staff_first_name
        description: "First name of the staff member"
        tests:
          - not_null

      - name: staff_last_name
        description: "Last name of the staff member"
        tests:
          - not_null

      - name: staff_email
        description: "Email address of the staff member"
        tests:
          - not_null

      - name: staff_phone
        description: "Phone number of the staff member"
        tests:
          - not_null

      - name: staff_is_active
        description: "Is the staff member is still active ? 1 -> Yes / 0 -> No"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "IN (0, 1)"

      - name: store_id
        description: "Secondary key to join the stores table. Id of the store where the staff is attached"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__stores')
                field: store_id

      - name: manager_id
        description: "Id of the manager's staff member (staff_id)"

  - name: int_local_bike__stocks
    description: "Stocks of the product by store"
    columns:
      - name: stock_id
        description: "Unique identify (Primary key) of the stock. Concatenation of store_id and product_id"
        tests:
          - not_null
          - unique

      - name: store_id
        description: "Secondary key to join the stores table. Id of the store where is the stock"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__stores')
                field: store_id

      - name: product_id
        description: "Secondary key to join the products table. Id of the product what is in the stock"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('int_local_bike__products')
                field: product_id

      - name: stock_quantity
        description: "Quantity of the product in the stock"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: ">= 0"

      - name: stock_value
        description: "Amount value of the product's stock in the store"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: ">= 0"

  - name: int_local_bike__stores
    description: "List of the stores owned by the company"
    columns:
      - name: store_id
        description: "Unique identify (Primary key) of the store"
        tests:
          - not_null
          - unique
          
      - name: store_name
        description: "Name of the store"
        tests:
          - not_null
          
      - name: store_phone
        description: "Phone number of the store"
        tests:
          - not_null
          
      - name: store_email
        description: "Email address of the store"
        tests:
          - not_null
          
      - name: store_street
        description: "Address street of the store"
        tests:
          - not_null
          
      - name: store_city
        description: "City of the store"
        tests:
          - not_null

      - name: store_state
        description: "State of the store"
        tests:
          - not_null

      - name: store_zip_code
        description: "Zip code of the store"
        tests:
          - not_null